version: '3'
services:
  petclinic:
    #image: anthonydahanne/spring-petclinic-clustered:4.3.2
    build: .
    ports:
      - "9966:9966"
    networks:
      - myTSANet
    environment:
      - TSA_URL=tsa1:9510,tsa2:9510
    links:
      - tsa1
      - tsa2
  tsa1:
    image: anthonydahanne/terracotta-server-oss:4.3.2
    hostname: tsa1
    networks:
      myTSANet:
        aliases:
          - tsa1
    ports:
      - "9510:9510"
      - "9530:9530"
    environment:
      - TC_SERVER1=tsa1
      - TC_SERVER2=tsa2
  tsa2:
    image: anthonydahanne/terracotta-server-oss:4.3.2
    hostname: tsa2
    networks:
      myTSANet:
        aliases:
          - tsa2
    ports:
      - "9610:9510"
      - "9630:9530"
    environment:
      - TC_SERVER1=tsa1
      - TC_SERVER2=tsa2
networks:
  myTSANet:
